name: release
permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.*"
    paths:
      - '.github/workflows/release.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.node-version'
    - name: npm install
      run: npm install
    - name: build
      run: npm run build
    - name: archive
      run: sudo tar jcvf /tmp/libnewbooks-frontend.tar.bz2 dist/*
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: |
          /tmp/libnewbooks-frontend.tar.bz2


